name: Test Notify slack
on:
  pull_request_target:
    types: [opened]
    branches:
      - '**'
jobs:
  notify:
    runs-on: ubuntu-latest
    name: A job to notify to slack new PR
    if: ${{ github.event.pull_request.user.login == 'chicus12' || github.event.pull_request.user.login == 'Jrojas19' }}
    steps:
    - name: Task from PR body
      id: task
      uses: chicus12/github-action-get-jira-task@main

    - name: Notify slack
      uses: pullreminders/slack-action@master
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      with:
        args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request:* <${{ github.event.pull_request.html_url }}|Ver Pull Request>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Creador:* ${{ github.event.pull_request.user.login }}\n*Estado:* ${{ github.event.pull_request.state }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Tareas:* ${{ steps.task.outputs.task }}\n${{ secrets.SLACK_TAGS }}\"}}]}'
